version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - gradle bootJar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/city-service-1.0-SNAPSHOT.jar